"""
Bull Run Probability Engine
Phase 8B — Multi-factor score: which stocks are positioned for a potential bull run

Combines four independent intelligence layers:
  1. Price Momentum Score (30%) — from price_momentum.csv [8A]
  2. Sector Capital Flow Score (25%) — FII_flow_score from sector_rotation_intelligence.csv [6C]
  3. Institutional Deal Score (25%) — inst_net_value_cr from institutional_deal_signals.csv [7A]
  4. Corporate Confidence Score (20%) — confidence_score_12m from corporate_confidence_scores.csv [7C]

Market Regime Multiplier applied after scoring:
  ACCUMULATION → ×1.10   DISTRIBUTION → ×0.80   otherwise → ×0.90

Labels:
  STRONG_CANDIDATE (>=65)  EMERGING (>=45)  WATCHLIST (>=30)
  NEUTRAL (>=15)           AVOID (<15)

Outputs:
  data/intelligence/bull_run_probability.csv   — all symbols with component scores
  data/intelligence/bull_run_watchlist.csv     — STRONG_CANDIDATE + EMERGING only

Guardrails: G-D-02 (atomic), G-D-03 (no empty write), G-I-04 (no fillna on financial data)
"""

import shutil
from pathlib import Path
import sys

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from engines.common import config as cfg
from engines.common.logger import get_logger

logger = get_logger("bull_run_probability")

INTELLIGENCE_DIR    = cfg.INTELLIGENCE_DIR
PRICE_MOMENTUM      = INTELLIGENCE_DIR / "price_momentum.csv"
SECTOR_ROTATION     = INTELLIGENCE_DIR / "sector_rotation_intelligence.csv"
DEAL_SIGNALS        = INTELLIGENCE_DIR / "institutional_deal_signals.csv"
CORPORATE_SCORES    = INTELLIGENCE_DIR / "corporate_confidence_scores.csv"
POSITIONING_HISTORY = cfg.DATA_DIR / "historical" / "institutional" / "institutional_positioning_history.csv"

OUTPUT_FULL      = INTELLIGENCE_DIR / "bull_run_probability.csv"
OUTPUT_WATCHLIST = INTELLIGENCE_DIR / "bull_run_watchlist.csv"

# Factor weights (must sum to 1.0)
WEIGHTS = {
    "price_score":       0.30,
    "sector_flow_score": 0.25,
    "deal_score":        0.25,
    "corporate_score":   0.20,
}

# Market regime multipliers
REGIME_MULTIPLIER = {
    "STRONG_ACCUMULATION": 1.20,
    "ACCUMULATION":        1.10,
    "EARLY_ACCUMULATION":  1.02,
    "NEUTRAL":             0.90,
    "DISTRIBUTION":        0.80,
    "STRONG_DISTRIBUTION": 0.65,
}
DEFAULT_MULTIPLIER = 0.90

# Bull run labels
LABEL_THRESHOLDS = [
    (65, "STRONG_CANDIDATE"),
    (45, "EMERGING"),
    (30, "WATCHLIST"),
    (15, "NEUTRAL"),
    (0,  "AVOID"),
]


def _label_score(score: float) -> str:
    for threshold, label in LABEL_THRESHOLDS:
        if score >= threshold:
            return label
    return "AVOID"


def _pct_rank_0_100(series: pd.Series) -> pd.Series:
    """Percentile rank to 0-100. NaN stays NaN."""
    return series.rank(pct=True, na_option="keep") * 100


class BullRunProbabilityEngine:
    """
    Phase 8B — full rebuild on each run.
    All factors must be pre-generated by their respective upstream engines.
    """

    def __init__(self):
        INTELLIGENCE_DIR.mkdir(parents=True, exist_ok=True)
        self._validate_inputs()

    def _validate_inputs(self):
        required = {
            "price_momentum.csv": PRICE_MOMENTUM,
            "sector_rotation_intelligence.csv": SECTOR_ROTATION,
        }
        missing = [name for name, path in required.items() if not path.exists()]
        if missing:
            raise FileNotFoundError(
                f"[8B] Required inputs missing — run upstream engines first: {missing}"
            )
        # Optional inputs (scored as neutral if absent)
        for path in [DEAL_SIGNALS, CORPORATE_SCORES, POSITIONING_HISTORY]:
            if not path.exists():
                logger.warning("[8B] Optional input missing (neutral fallback): %s", path.name)

    # ----------------------------------------------------------------
    # Factor loaders — each returns a Series indexed by symbol
    # ----------------------------------------------------------------

    def _load_price_scores(self) -> pd.DataFrame:
        df = pd.read_csv(PRICE_MOMENTUM)
        df["symbol"] = df["symbol"].str.strip().str.upper()
        df = df.set_index("symbol")
        # price_score is already 0-100 from 8A
        return df[["price_score", "sector", "close_now", "ret_30d", "ret_90d",
                    "ret_365d", "vol_ratio", "as_of_date"]].copy()

    def _load_sector_flow_scores(self) -> pd.Series:
        """FII_flow_score (±100 z-score) → normalised 0-100 per sector."""
        df = pd.read_csv(SECTOR_ROTATION, usecols=["sector", "FII_flow_score"])
        df["sector"] = df["sector"].str.strip().str.upper()
        df = df.groupby("sector")["FII_flow_score"].last()
        # Rescale ±100 to 0-100
        normalised = ((df + 100) / 2).clip(0, 100)
        return normalised

    def _load_deal_scores(self) -> pd.Series:
        """inst_net_value_cr percentile-ranked to 0-100. NaN → 50 (neutral)."""
        if not DEAL_SIGNALS.exists():
            return pd.Series(dtype=float, name="deal_score")
        df = pd.read_csv(DEAL_SIGNALS, usecols=["symbol", "inst_net_value_cr"])
        df["symbol"] = df["symbol"].str.strip().str.upper()
        df = df.set_index("symbol")
        ranked = _pct_rank_0_100(df["inst_net_value_cr"])
        return ranked.rename("deal_score")

    def _load_corporate_scores(self) -> pd.Series:
        """confidence_score_12m clipped [-3, 6] → rescaled 0-100. NaN → 50."""
        if not CORPORATE_SCORES.exists():
            return pd.Series(dtype=float, name="corporate_score")
        df = pd.read_csv(CORPORATE_SCORES, usecols=["symbol", "confidence_score_12m"])
        df["symbol"] = df["symbol"].str.strip().str.upper()
        df = df.set_index("symbol")
        s = df["confidence_score_12m"].clip(-3, 6)
        normalised = ((s + 3) / 9 * 100).round(2)
        return normalised.rename("corporate_score")

    def _load_market_regime(self) -> tuple[str, float]:
        """Returns (regime_label, multiplier). Falls back to DISTRIBUTION if unreadable."""
        if not POSITIONING_HISTORY.exists():
            logger.warning("[8B] Positioning history not found — using DISTRIBUTION regime")
            return "DISTRIBUTION", REGIME_MULTIPLIER["DISTRIBUTION"]
        df = pd.read_csv(POSITIONING_HISTORY, usecols=["Date", "Regime"])
        if df.empty or "Regime" not in df.columns:
            return "DISTRIBUTION", REGIME_MULTIPLIER["DISTRIBUTION"]
        latest_regime = df.dropna(subset=["Regime"])["Regime"].iloc[-1]
        multiplier = REGIME_MULTIPLIER.get(latest_regime, DEFAULT_MULTIPLIER)
        logger.info("[8B] Market regime: %s (multiplier x%.2f)", latest_regime, multiplier)
        return latest_regime, multiplier

    # ----------------------------------------------------------------
    # Scoring
    # ----------------------------------------------------------------

    def run(self) -> bool:
        logger.info("[BullRunProbability] Starting Phase 8B")

        base     = self._load_price_scores()
        sec_flow = self._load_sector_flow_scores()     # keyed by sector
        deal_s   = self._load_deal_scores()            # keyed by symbol
        corp_s   = self._load_corporate_scores()       # keyed by symbol
        regime, multiplier = self._load_market_regime()

        # Attach sector flow score via sector mapping
        base["sector_flow_score"] = base["sector"].map(sec_flow).fillna(50).round(2)

        # Attach deal score (neutral 50 for unknown symbols)
        base["deal_score"] = deal_s.reindex(base.index).fillna(50).round(2)

        # Attach corporate score (neutral 50 for unknown symbols)
        base["corporate_score"] = corp_s.reindex(base.index).fillna(50).round(2)

        # Base composite score
        base["base_score"] = (
            base["price_score"]       * WEIGHTS["price_score"]
            + base["sector_flow_score"] * WEIGHTS["sector_flow_score"]
            + base["deal_score"]        * WEIGHTS["deal_score"]
            + base["corporate_score"]   * WEIGHTS["corporate_score"]
        ).round(2)

        # Apply market regime multiplier then clip to [0, 100]
        base["market_regime"]     = regime
        base["regime_multiplier"] = multiplier
        base["bull_run_score"]    = (base["base_score"] * multiplier).clip(0, 100).round(2)
        base["label"]             = base["bull_run_score"].apply(_label_score)

        result = base.reset_index()

        # Column order
        cols = [
            "symbol", "sector", "close_now", "as_of_date",
            "price_score", "sector_flow_score", "deal_score", "corporate_score",
            "base_score", "market_regime", "regime_multiplier", "bull_run_score", "label",
            "ret_30d", "ret_90d", "ret_365d", "vol_ratio",
        ]
        result = result[[c for c in cols if c in result.columns]]

        if result.empty:
            raise ValueError("G-D-03: bull run result is empty")

        # Watchlist (strong signals only)
        watchlist = result[result["label"].isin(["STRONG_CANDIDATE", "EMERGING"])].copy()
        watchlist = watchlist.sort_values("bull_run_score", ascending=False).reset_index(drop=True)

        self._save_atomic(result.sort_values("bull_run_score", ascending=False)
                               .reset_index(drop=True), OUTPUT_FULL)
        self._save_atomic(watchlist, OUTPUT_WATCHLIST)
        self._print_summary(result, watchlist, regime, multiplier)
        return True

    # ----------------------------------------------------------------
    # Save + Print
    # ----------------------------------------------------------------

    def _save_atomic(self, df: pd.DataFrame, path: Path):
        tmp = path.with_suffix(".tmp")
        df.to_csv(tmp, index=False)
        shutil.move(str(tmp), str(path))
        logger.info("[8B] Saved %s (%d rows)", path.name, len(df))

    def _print_summary(self, result: pd.DataFrame, watchlist: pd.DataFrame,
                       regime: str, multiplier: float):
        print()
        print("=" * 65)
        print("BULL RUN PROBABILITY ENGINE - PHASE 8B COMPLETE")
        print("=" * 65)
        print(f"Symbols scored        : {len(result)}")
        print(f"Market regime         : {regime} (x{multiplier:.2f})")
        print(f"Score range           : {result['bull_run_score'].min():.0f} to "
              f"{result['bull_run_score'].max():.0f}")
        print()
        label_counts = result["label"].value_counts()
        for label, count in label_counts.items():
            print(f"  {label:22s}: {count:4d} symbols")
        print()
        print(f"Watchlist (STRONG + EMERGING): {len(watchlist)} symbols")
        if not watchlist.empty:
            print("\nTop 10 bull run candidates:")
            for _, r in watchlist.head(10).iterrows():
                deal_flag  = "" if r["deal_score"] == 50 else f" deal={r['deal_score']:.0f}"
                corp_flag  = "" if r["corporate_score"] == 50 else f" corp={r['corporate_score']:.0f}"
                print(f"  {r['symbol']:15s}: score={r['bull_run_score']:.0f}"
                      f"  price={r['price_score']:.0f}"
                      f"  sec_flow={r['sector_flow_score']:.0f}"
                      f"{deal_flag}{corp_flag}"
                      f"  ({r['label']})")
        print()
        print("Sector breakdown (STRONG_CANDIDATE):")
        sc = result[result["label"] == "STRONG_CANDIDATE"]
        if not sc.empty:
            sector_cnt = sc["sector"].value_counts().head(8)
            for sec, cnt in sector_cnt.items():
                print(f"  {sec:22s}: {cnt}")
        print("=" * 65)


if __name__ == "__main__":
    engine = BullRunProbabilityEngine()
    engine.run()
