"""
Platform Configuration
Single source of truth for paths and runtime settings.
"""

import os
from pathlib import Path
try:
    from dotenv import load_dotenv
except ImportError:  # pragma: no cover - fallback for lean runtime envs
    def load_dotenv(*args, **kwargs):  # type: ignore[override]
        return False

# Load .env from project root — makes TELEGRAM_BOT_TOKEN, ANTHROPIC_API_KEY etc.
# available via os.getenv() in every engine without manual shell export.
load_dotenv(Path(__file__).resolve().parents[2] / ".env", override=False)

# ==========================================================
# PROJECT ROOT
# ==========================================================

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

# ==========================================================
# DATA ROOT
# ==========================================================

DATA_DIR = PROJECT_ROOT / "data"

NSE_DIR = DATA_DIR / "NSE"
BSE_DIR = DATA_DIR / "BSE"

CACHE_DIR = NSE_DIR / "nsecache"

REFERENCE_DIR = DATA_DIR / "reference"
INTELLIGENCE_DIR = DATA_DIR / "intelligence"

# ==========================================================
# DOCUMENTATION / LOGS
# ==========================================================

LOG_DIR = PROJECT_ROOT / "logs"
DOCS_DIR = PROJECT_ROOT / "docs"


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    return raw.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name: str, default: int) -> int:
    raw = os.getenv(name)
    if raw is None:
        return default
    try:
        return int(raw.strip())
    except ValueError:
        return default


def _env_str(name: str, default: str) -> str:
    raw = os.getenv(name)
    return raw.strip() if raw and raw.strip() else default

# ==========================================================
# NSE PATHS
# ==========================================================

BHAVCOPY_DIR = NSE_DIR / "bhavcopy"

NSE_EQUITY_BHAVCOPY_DIR = BHAVCOPY_DIR / "equity"
NSE_FNO_BHAVCOPY_DIR = BHAVCOPY_DIR / "fno"

INDICES_DIR = NSE_DIR / "indices"
REPORTS_DIR = NSE_DIR / "reports"

EQUITY_MASTER_DIR = NSE_DIR / "equity_master"

CORPORATE_ACTIONS_DIR = NSE_DIR / "corporate_actions"
RESULTS_DIR = NSE_DIR / "results"
SHAREHOLDING_DIR = NSE_DIR / "shareholding"
ADJUSTED_EQUITY_DIR = NSE_DIR / "adjusted_equity"
FPI_DIR = NSE_DIR / "fpi"

# ==========================================================
# BSE PATHS (Future)
# ==========================================================

BSE_BHAVCOPY_DIR = BSE_DIR / "bhavcopy"

BSE_EQUITY_BHAVCOPY_DIR = BSE_BHAVCOPY_DIR / "equity"
BSE_FNO_BHAVCOPY_DIR = BSE_BHAVCOPY_DIR / "fno"

# ==========================================================
# CACHE
# ==========================================================

STOCK_HISTORY_CACHE = CACHE_DIR / "stock_history"
REPORT_CACHE = CACHE_DIR / "reports"

# ==========================================================
# VEDA RESEARCH / ATTACHMENTS
# ==========================================================

VEDA_CACHE_DIR = DATA_DIR / "veda"
VEDA_RESEARCH_CACHE_DIR = VEDA_CACHE_DIR / "research_cache"
VEDA_CHAT_UPLOAD_DIR = VEDA_CACHE_DIR / "uploads"
VEDA_CHAT_SESSION_DIR = VEDA_CACHE_DIR / "chat_sessions"
VEDA_RETRIEVAL_AUDIT_DIR = VEDA_CACHE_DIR / "retrieval_audits"
VEDA_KNOWLEDGE_REVIEW_DIR = VEDA_CACHE_DIR / "knowledge_reviews"
VEDA_KNOWLEDGE_DRAFT_DIR = VEDA_KNOWLEDGE_REVIEW_DIR / "drafts"
VEDA_KNOWLEDGE_APPROVED_DIR = VEDA_KNOWLEDGE_REVIEW_DIR / "approved"
VEDA_APPROVED_KNOWLEDGE_DOCS = INTELLIGENCE_DIR / "rag_knowledge" / "veda_reviewed_documents.jsonl"
VEDA_CAPABILITY_REVIEW_DIR = VEDA_CACHE_DIR / "capability_reviews"
VEDA_CAPABILITY_DRAFT_DIR = VEDA_CAPABILITY_REVIEW_DIR / "drafts"
VEDA_CAPABILITY_APPROVED_DIR = VEDA_CAPABILITY_REVIEW_DIR / "approved"
VEDA_APPROVED_CAPABILITY_DOCS = INTELLIGENCE_DIR / "rag_knowledge" / "veda_capability_documents.jsonl"
VEDA_UNIFIED_KNOWLEDGE_DOCS = INTELLIGENCE_DIR / "rag_knowledge" / "veda_unified_documents.jsonl"
VEDA_UNIFIED_KNOWLEDGE_MANIFEST = INTELLIGENCE_DIR / "rag_knowledge" / "veda_unified_manifest.json"
VEDA_UNIFIED_KNOWLEDGE_METADATA = INTELLIGENCE_DIR / "rag_knowledge" / "veda_unified_metadata.csv"
VEDA_UNIFIED_BM25_INDEX = INTELLIGENCE_DIR / "rag_knowledge" / "veda_unified_bm25_index.pkl"
VEDA_UNIFIED_FAISS_DIR = INTELLIGENCE_DIR / "rag_knowledge" / "veda_unified_faiss"
VEDA_UNIFIED_RETRIEVAL_BENCHMARK_PATH = DOCS_DIR / "governance" / "fixtures" / "veda_unified_retrieval_benchmark.json"
VEDA_UNIFIED_RETRIEVAL_BENCHMARK_REPORT_DIR = VEDA_RETRIEVAL_AUDIT_DIR / "benchmark_reports"
VEDA_UNIFIED_RETRIEVAL_SHADOW_LOG = VEDA_RETRIEVAL_AUDIT_DIR / "veda_unified_shadow_runs.jsonl"
VEDA_RESEARCH_PLATFORM_DIR = DATA_DIR / "research"
VEDA_RESEARCH_PLATFORM_RUNTIME_DIR = VEDA_RESEARCH_PLATFORM_DIR / "runtime"
VEDA_RESEARCH_PLATFORM_DB = VEDA_RESEARCH_PLATFORM_RUNTIME_DIR / "research_platform.sqlite3"
VEDA_RESEARCH_PLATFORM_FIXTURE_DIR = VEDA_RESEARCH_PLATFORM_DIR / "fixtures"
VEDA_RESEARCH_PLATFORM_EXPORT_DIR = VEDA_RESEARCH_PLATFORM_DIR / "synthetic_pilot"
VEDA_ASTROLOGY_RESEARCH_DIR = VEDA_CACHE_DIR / "research" / "astrology"
VEDA_ASTROLOGY_SOURCE_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "sources"
VEDA_ASTROLOGY_PASSAGE_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "passages"
VEDA_ASTROLOGY_CLAIM_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "claims"
VEDA_ASTROLOGY_CONFLICT_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "conflicts"
VEDA_ASTROLOGY_APPROVAL_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "approvals"
VEDA_ASTROLOGY_POLICY_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "policies"
VEDA_ASTROLOGY_LEGACY_DIR = VEDA_ASTROLOGY_RESEARCH_DIR / "legacy"
VEDA_ASTROLOGY_ONTOLOGY_DIR = VEDA_CACHE_DIR / "ontology"
VEDA_ASTROLOGY_RELATION_DIR = VEDA_ASTROLOGY_ONTOLOGY_DIR / "relations"
VEDA_ASTROLOGY_RULE_DIR = VEDA_CACHE_DIR / "rules"
VEDA_ASTROLOGY_RULE_DRAFT_DIR = VEDA_ASTROLOGY_RULE_DIR / "draft"
VEDA_ASTROLOGY_RULE_APPROVED_DIR = VEDA_ASTROLOGY_RULE_DIR / "approved"
VEDA_ASTROLOGY_RULE_LEGACY_MAPPING_DIR = VEDA_ASTROLOGY_RULE_DIR / "legacy_mappings"
VEDA_ASTROLOGY_RULE_CONTRACT_DIR = VEDA_ASTROLOGY_RULE_DIR / "contracts"

VEDA_RESEARCH_ENABLED = _env_bool("VEDA_RESEARCH_ENABLED", True)
VEDA_RESEARCH_PLATFORM_VERSION = "2026-08-10"
VEDA_KNOWLEDGE_CONTRACT_VERSION = "2026-08-04"
VEDA_ASTROLOGY_GOVERNANCE_VERSION = "2026-08-10"
VEDA_ASTROLOGY_ONTOLOGY_VERSION = "2026-08-10"
VEDA_PLATFORM_ML_MODEL_NAME = _env_str("VEDA_PLATFORM_ML_MODEL_NAME", "bull_run_score_pipeline")
VEDA_PLATFORM_ML_MODEL_VERSION = _env_str("VEDA_PLATFORM_ML_MODEL_VERSION", "2026-08-04")
VEDA_UNIFIED_RETRIEVAL_ENABLED = _env_bool("VEDA_UNIFIED_RETRIEVAL_ENABLED", True)
VEDA_UNIFIED_RETRIEVAL_SHADOW_ENABLED = _env_bool("VEDA_UNIFIED_RETRIEVAL_SHADOW_ENABLED", False)
VEDA_UNIFIED_RETRIEVAL_SHADOW_WRITE_LOG = _env_bool("VEDA_UNIFIED_RETRIEVAL_SHADOW_WRITE_LOG", True)
VEDA_UNIFIED_RETRIEVAL_SYNC_ON_SAVE = _env_bool("VEDA_UNIFIED_RETRIEVAL_SYNC_ON_SAVE", True)
VEDA_UNIFIED_FAISS_SYNC_ON_SAVE = _env_bool("VEDA_UNIFIED_FAISS_SYNC_ON_SAVE", False)
VEDA_UNIFIED_FAISS_LOCAL_ONLY_ON_SAVE = _env_bool("VEDA_UNIFIED_FAISS_LOCAL_ONLY_ON_SAVE", True)
VEDA_UNIFIED_RETRIEVAL_TOP_K = _env_int("VEDA_UNIFIED_RETRIEVAL_TOP_K", 6)
VEDA_UNIFIED_RETRIEVAL_CONTEXT_TOP_K = _env_int("VEDA_UNIFIED_RETRIEVAL_CONTEXT_TOP_K", 4)
VEDA_RESEARCH_AUTO_FOR_RESEARCH_INTENT = _env_bool("VEDA_RESEARCH_AUTO_FOR_RESEARCH_INTENT", False)
VEDA_RESEARCH_PROVIDER = _env_str("VEDA_RESEARCH_PROVIDER", "ddgs")
VEDA_RESEARCH_REGION = _env_str("VEDA_RESEARCH_REGION", "in-en")
VEDA_RESEARCH_TIMEOUT_S = _env_int("VEDA_RESEARCH_TIMEOUT_S", 8)
VEDA_RESEARCH_MAX_RESULTS = _env_int("VEDA_RESEARCH_MAX_RESULTS", 5)
VEDA_RESEARCH_NEWS_RESULTS = _env_int("VEDA_RESEARCH_NEWS_RESULTS", 2)
VEDA_RESEARCH_MAX_QUERY_CHARS = _env_int("VEDA_RESEARCH_MAX_QUERY_CHARS", 320)
VEDA_RESEARCH_MAX_SNIPPET_CHARS = _env_int("VEDA_RESEARCH_MAX_SNIPPET_CHARS", 280)
VEDA_RESEARCH_CACHE_TTL_S = _env_int("VEDA_RESEARCH_CACHE_TTL_S", 900)
VEDA_ATTACHMENTS_ENABLED = _env_bool("VEDA_ATTACHMENTS_ENABLED", True)
VEDA_SAVE_TO_KNOWLEDGE_ENABLED = _env_bool("VEDA_SAVE_TO_KNOWLEDGE_ENABLED", True)
VEDA_MIT_REPO_INTAKE_ENABLED = _env_bool("VEDA_MIT_REPO_INTAKE_ENABLED", True)
VEDA_MCP_ENABLED = _env_bool("VEDA_MCP_ENABLED", False)
VEDA_MCP_SERVER_CONFIG = _env_str("VEDA_MCP_SERVER_CONFIG", str(VEDA_CACHE_DIR / "mcp_servers.json"))
VEDA_MCP_PROTOCOL_VERSION = _env_str("VEDA_MCP_PROTOCOL_VERSION", "2025-06-18")
VEDA_MCP_CLIENT_NAME = _env_str("VEDA_MCP_CLIENT_NAME", "veda-research")
VEDA_MCP_TIMEOUT_S = _env_int("VEDA_MCP_TIMEOUT_S", 12)
VEDA_MCP_MAX_RESULTS = _env_int("VEDA_MCP_MAX_RESULTS", 5)
VEDA_MCP_SERVER_ORDER = _env_str("VEDA_MCP_SERVER_ORDER", "github,ddgs,tavily,exa,firecrawl,fetch")
VEDA_ATTACHMENT_MAX_FILE_BYTES = _env_int("VEDA_ATTACHMENT_MAX_FILE_BYTES", 12 * 1024 * 1024)
VEDA_ATTACHMENT_MAX_FILES = _env_int("VEDA_ATTACHMENT_MAX_FILES", 4)
VEDA_ATTACHMENT_MAX_TEXT_CHARS = _env_int("VEDA_ATTACHMENT_MAX_TEXT_CHARS", 12000)
VEDA_ATTACHMENT_MAX_TOTAL_PROMPT_CHARS = _env_int("VEDA_ATTACHMENT_MAX_TOTAL_PROMPT_CHARS", 18000)
VEDA_ATTACHMENT_EXCERPT_CHARS = _env_int("VEDA_ATTACHMENT_EXCERPT_CHARS", 260)
VEDA_ATTACHMENT_MAX_PDF_PAGES = _env_int("VEDA_ATTACHMENT_MAX_PDF_PAGES", 6)
VEDA_ATTACHMENT_MAX_TABLE_ROWS = _env_int("VEDA_ATTACHMENT_MAX_TABLE_ROWS", 20)
VEDA_ATTACHMENT_MAX_TABLE_COLS = _env_int("VEDA_ATTACHMENT_MAX_TABLE_COLS", 12)
VEDA_ATTACHMENT_VISION_ENABLED = _env_bool("VEDA_ATTACHMENT_VISION_ENABLED", True)
VEDA_ATTACHMENT_VISION_MODEL = _env_str("VEDA_ATTACHMENT_VISION_MODEL", "gpt-4o-mini")
VEDA_ATTACHMENT_VISION_MAX_TOKENS = _env_int("VEDA_ATTACHMENT_VISION_MAX_TOKENS", 350)
VEDA_ATTACHMENT_VISION_TIMEOUT_S = _env_int("VEDA_ATTACHMENT_VISION_TIMEOUT_S", 20)
VEDA_CHAT_MAX_HISTORY_MESSAGES = _env_int("VEDA_CHAT_MAX_HISTORY_MESSAGES", 12)
VEDA_CHAT_MAX_HISTORY_CHARS = _env_int("VEDA_CHAT_MAX_HISTORY_CHARS", 24000)
VEDA_CHAT_MAX_MESSAGE_CHARS = _env_int("VEDA_CHAT_MAX_MESSAGE_CHARS", 4000)
VEDA_CHAT_MAX_SYSTEM_PROMPT_CHARS = _env_int("VEDA_CHAT_MAX_SYSTEM_PROMPT_CHARS", 26000)
VEDA_CHAT_MAX_TOOL_RESULT_CHARS = _env_int("VEDA_CHAT_MAX_TOOL_RESULT_CHARS", 12000)
VEDA_CHAT_PROVIDER_CONNECTION_COOLDOWN_S = _env_int("VEDA_CHAT_PROVIDER_CONNECTION_COOLDOWN_S", 120)
VEDA_CHAT_PROVIDER_HARD_FAILURE_COOLDOWN_S = _env_int("VEDA_CHAT_PROVIDER_HARD_FAILURE_COOLDOWN_S", 3600)
VEDA_KNOWLEDGE_MAX_TITLE_CHARS = _env_int("VEDA_KNOWLEDGE_MAX_TITLE_CHARS", 120)
VEDA_KNOWLEDGE_MAX_SUMMARY_CHARS = _env_int("VEDA_KNOWLEDGE_MAX_SUMMARY_CHARS", 1200)
VEDA_KNOWLEDGE_MAX_FACTS = _env_int("VEDA_KNOWLEDGE_MAX_FACTS", 6)
VEDA_KNOWLEDGE_MAX_TAGS = _env_int("VEDA_KNOWLEDGE_MAX_TAGS", 8)
VEDA_KNOWLEDGE_ATTACHMENT_CHUNK_CHARS = _env_int("VEDA_KNOWLEDGE_ATTACHMENT_CHUNK_CHARS", 1400)
VEDA_KNOWLEDGE_ATTACHMENT_CHUNK_OVERLAP_CHARS = _env_int("VEDA_KNOWLEDGE_ATTACHMENT_CHUNK_OVERLAP_CHARS", 180)
VEDA_KNOWLEDGE_ATTACHMENT_MAX_CHUNKS_PER_FILE = _env_int("VEDA_KNOWLEDGE_ATTACHMENT_MAX_CHUNKS_PER_FILE", 8)
VEDA_MIT_REPO_MAX_SCAN_FILES = _env_int("VEDA_MIT_REPO_MAX_SCAN_FILES", 2500)
VEDA_MIT_REPO_MAX_FILE_BYTES = _env_int("VEDA_MIT_REPO_MAX_FILE_BYTES", 180000)
VEDA_MIT_REPO_MAX_CANDIDATE_FILES = _env_int("VEDA_MIT_REPO_MAX_CANDIDATE_FILES", 8)
VEDA_MIT_REPO_MAX_FILE_CHARS = _env_int("VEDA_MIT_REPO_MAX_FILE_CHARS", 2600)
VEDA_MIT_REPO_LICENSE_EXCERPT_CHARS = _env_int("VEDA_MIT_REPO_LICENSE_EXCERPT_CHARS", 320)

# ==========================================================
# HOLIDAYS
# ==========================================================

NSE_HOLIDAY_FILE = REFERENCE_DIR / "nse_holidays.csv"
SPECIAL_SESSIONS_FILE = REFERENCE_DIR / "special_trading_sessions.csv"


# ==========================================================
# ACQUISITION SETTINGS
# ==========================================================

NSE_EQUITY_START_YEAR = 1995
NSE_FNO_START_YEAR = 2000
CORPORATE_ACTION_START_YEAR = 1995

# ============================================================
# VALIDATION WINDOWS
# ============================================================

NSE_EQUITY_VALIDATION_YEARS = 5
NSE_FNO_VALIDATION_YEARS = 5

# ============================================================
# WORKERS
# ============================================================

MIN_CONCURRENCY = 4
MAX_CONCURRENCY = 6

# ============================================================
# OUTPUT
# ============================================================

WRITE_CSV = True
WRITE_PARQUET = True

API_TIMEOUT = 30
API_DELAY = 1.0

MAX_RETRIES = 3
RETRY_DELAY = 3

# ==========================================================
# DIRECTORY INITIALIZATION
# ==========================================================

DIRECTORIES = [
    DATA_DIR,
    NSE_DIR,
    BSE_DIR,
    CACHE_DIR,
    REFERENCE_DIR,
    INTELLIGENCE_DIR,
    LOG_DIR,
    VEDA_CACHE_DIR,
    VEDA_RESEARCH_CACHE_DIR,
    VEDA_CHAT_UPLOAD_DIR,
    VEDA_CHAT_SESSION_DIR,
    VEDA_RETRIEVAL_AUDIT_DIR,
    VEDA_UNIFIED_RETRIEVAL_BENCHMARK_REPORT_DIR,
    VEDA_RESEARCH_PLATFORM_DIR,
    VEDA_RESEARCH_PLATFORM_RUNTIME_DIR,
    VEDA_RESEARCH_PLATFORM_FIXTURE_DIR,
    VEDA_RESEARCH_PLATFORM_EXPORT_DIR,
    VEDA_ASTROLOGY_RESEARCH_DIR,
    VEDA_ASTROLOGY_SOURCE_DIR,
    VEDA_ASTROLOGY_PASSAGE_DIR,
    VEDA_ASTROLOGY_CLAIM_DIR,
    VEDA_ASTROLOGY_CONFLICT_DIR,
    VEDA_ASTROLOGY_APPROVAL_DIR,
    VEDA_ASTROLOGY_POLICY_DIR,
    VEDA_ASTROLOGY_LEGACY_DIR,
    VEDA_ASTROLOGY_ONTOLOGY_DIR,
    VEDA_ASTROLOGY_RELATION_DIR,
    VEDA_ASTROLOGY_RULE_DIR,
    VEDA_ASTROLOGY_RULE_DRAFT_DIR,
    VEDA_ASTROLOGY_RULE_APPROVED_DIR,
    VEDA_ASTROLOGY_RULE_LEGACY_MAPPING_DIR,
    VEDA_ASTROLOGY_RULE_CONTRACT_DIR,
    VEDA_KNOWLEDGE_REVIEW_DIR,
    VEDA_KNOWLEDGE_DRAFT_DIR,
    VEDA_KNOWLEDGE_APPROVED_DIR,
    VEDA_APPROVED_KNOWLEDGE_DOCS.parent,
    VEDA_CAPABILITY_REVIEW_DIR,
    VEDA_CAPABILITY_DRAFT_DIR,
    VEDA_CAPABILITY_APPROVED_DIR,
    VEDA_APPROVED_CAPABILITY_DOCS.parent,
    VEDA_UNIFIED_KNOWLEDGE_DOCS.parent,
    VEDA_UNIFIED_FAISS_DIR,

    NSE_EQUITY_BHAVCOPY_DIR,
    NSE_FNO_BHAVCOPY_DIR,

    BSE_EQUITY_BHAVCOPY_DIR,
    BSE_FNO_BHAVCOPY_DIR,

    EQUITY_MASTER_DIR,
    CORPORATE_ACTIONS_DIR,
    ADJUSTED_EQUITY_DIR,
    FPI_DIR,
]

for directory in DIRECTORIES:
    directory.mkdir(
        parents=True,
        exist_ok=True
    )
